home layout first version
nearcomponents/extension-wallet pull request #1
Opened 2021-12-07 22:46 UTC by sergiogaguero

2021-12-09 13:59 UTC, leomanza requested changes

2021-12-09 13:59 UTC, leomanza commented on src/views/Home/Home.tsx
> +                <input type="text"  ref={inputRef } onChange={(val)=> onChangeInput(val)} placeholder={typeLogin === LOGIN_TYPE.PHONE ? "Ex. (373) 378 8383" : "jhondoe@gmail.com"} className="home__se
get rid of ref usage

2021-12-09 13:59 UTC, leomanza commented on src/views/Home/Home.tsx
> +                <input type="text"  ref={inputRef } onChange={(val)=> onChangeInput(val)} placeholder={typeLogin === LOGIN_TYPE.PHONE ? "Ex. (373) 378 8383" : "jhondoe@gmail.com"} className="home__se
you can simply do : onChange={onChangeInput}
then the function must start with:
   const onChangeInput= (val: any) => {

2021-12-09 13:59 UTC, leomanza commented on src/views/Home/Home.tsx
> +    const [isValid, setIsValid] = useState(false);
use types on useStates with a specific type (avoid any if possible):
eg:
const [isValid, setIsValid] = useState<boolean | null>(false);
instead of 
  const [isValid, setIsValid] = useState(false);

2021-12-09 20:32 UTC, sergiogaguero commented on src/views/Home/Home.tsx
> +    const [isValid, setIsValid] = useState(false);
El unico que le tuve que dejar any es el state del input que al usarlo en el ref no le gustaba el tipo string.

2021-12-10 21:20 UTC, leomanza approved these changes
looks good

2021-12-10 21:53 UTC, merged