Ex 27 create contact and edit
nearcomponents/extension-wallet pull request #44
Opened 2022-01-17 21:28 UTC by sergiogaguero

2022-01-17 23:25 UTC, leomanza requested changes
just a comment about a hardcoded url

2022-01-17 23:25 UTC, leomanza commented on src/services/contacts.ts
> +export const apiNearUrl = `${process.env.NEARAPI_BACKEND}`;'https://api.nearlogin.io';
was '**https://api.nearlogin.io'**;  added here on purpose?

2022-01-17 23:58 UTC, sergiogaguero commented on src/services/contacts.ts
> +export const apiNearUrl = `${process.env.NEARAPI_BACKEND}`;'https://api.nearlogin.io';
my bad!, must be a copy/paste error.

2022-01-18 00:00 UTC, sergiogaguero commented on src/services/contacts.ts
> +export const apiNearUrl = `${process.env.NEARAPI_BACKEND}`;'https://api.nearlogin.io';
Fixed

2022-01-18 00:20 UTC, merged